<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سنتز ویژگی
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
ابتدا نیاز است فایل مجموعه‌داده‌ی بدون مقادیر گم‌شده (<code>beijing_no_missing.csv</code>) را بخوانیم.
</p>

In [1]:
import pandas as pd
# reading the dataset
df = pd.read_csv('beijing_no_missing.csv', encoding='gbk', low_memory=False)

/home/amin/Desktop/Jump Machine Learning/qenv/lib/python3.9/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [2]:
df

,url,id,Lng,Lat,Cid,tradeTime,DOM,followers,totalPrice,price,...,buildingStructure,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage,price_category,buildingStrucure_ismissing,buildingType_ismissing
0,https://bj.lianjia.com/chengjiao/101084782030....,101084782030,116.475489,40.019520,1111027376244,2016-08-09,1464.0,106,415.0,31680,...,steel-concrete composite,0.217,has elevator,no,has subway,7,56021.0,average,False,False
1,https://bj.lianjia.com/chengjiao/101086012217....,101086012217,116.453917,39.881534,1111027381879,2016-07-28,903.0,126,575.0,43436,...,steel-concrete composite,0.667,has elevator,yes,no subway,7,71539.0,average,False,False
2,https://bj.lianjia.com/chengjiao/101086041636....,101086041636,116.561978,39.877145,1111040862969,2016-12-11,1271.0,48,1030.0,52021,...,steel-concrete composite,0.500,has elevator,no,no subway,7,48160.0,average,False,False
3,https://bj.lianjia.com/chengjiao/101086406841....,101086406841,116.438010,40.076114,1111043185817,2016-09-30,965.0,138,297.5,22202,...,steel-concrete composite,0.273,has elevator,no,no subway,6,51238.0,cheap,False,False
4,https://bj.lianjia.com/chengjiao/101086920653....,101086920653,116.428392,39.886229,1111027381174,2016-08-28,927.0,286,392.0,48396,...,mixed,0.333,no elevator,yes,has subway,1,62588.0,average,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318814,https://bj.lianjia.com/chengjiao/BJYZ92311192....,BJYZ92311192,116.546899,39.755236,1111027377053,2016-06-10,1.0,8,350.0,20580,...,steel-concrete composite,0.333,no elevator,yes,no subway,3,36545.0,cheap,False,False
318815,https://bj.lianjia.com/chengjiao/BJYZ92320171....,BJYZ92320171,116.497474,39.810115,1111027377957,2016-06-10,1.0,1,108.8,31006,...,steel-concrete composite,0.222,has elevator,no,has subway,3,54282.0,average,False,False
318816,https://bj.lianjia.com/chengjiao/BJYZ92324217....,BJYZ92324217,116.497256,39.804081,1111027380056,2016-06-05,1.0,2,359.0,35138,...,steel-concrete composite,0.500,has elevator,yes,no subway,3,46927.0,average,False,False
318817,https://bj.lianjia.com/chengjiao/BJYZ92333313....,BJYZ92333313,116.501794,39.799347,1111027377054,2016-06-12,10.0,4,720.0,40373,...,mixed,0.500,no elevator,yes,no subway,3,54842.0,average,False,False
318818,https://bj.lianjia.com/chengjiao/BJYZ92363553....,BJYZ92363553,116.497474,39.810115,1111027377957,2016-06-11,1.0,0,450.0,48675,...,steel-concrete composite,1.000,has elevator,no,has subway,3,54282.0,average,False,False

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
تعریف ویژگی‌های جدید
</font>
</h2>

In [3]:
import datetime
import numpy as np

# creating the featuers
current_year = datetime.datetime.now().year
print('Current year:', current_year)

# Latitude and Longitude of Bejing (from http://latlong.net/place/beijing-china-27567.html)
bejing_center_Lng = 116.383331
bejing_center_Lat = 39.916668

df['number_of_rooms'] = df['livingRoom'] + df['drawingRoom']

# convert the constructionTime column to int
df['constructionTime'] = df['constructionTime'].astype(int)
# calculate the age of the house
df['age'] = current_year - df['constructionTime']

# calculate the Euclidean distance from the city center

df['distance_to_city_center'] = ((df['Lat'] - bejing_center_Lat)**2 + (df['Lng'] - bejing_center_Lng)**2) ** (1/2)

# calculate the angle in degrees
df['angle_degrees'] = np.degrees(np.arctan((df['Lat'] - bejing_center_Lat)/(df['Lng'] - bejing_center_Lng)))

df[['id', 'number_of_rooms', 'age', 'distance_to_city_center', 'angle_degrees']].head()

Current year: 2023

             id  number_of_rooms  age  distance_to_city_center  angle_degrees
0  101084782030                3   18                 0.138100      48.138854
1  101086012217                4   19                 0.078847     -26.461708
2  101086041636                5   18                 0.182967     -12.474904
3  101086406841                4   15                 0.168561      71.071561
4  101086920653                3   63                 0.054379     -34.039283

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
گسسته‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
حال می‌خواهیم که ستون <code>constructionTime​</code> را انتخاب کرده و آن را گسسته‌ کنیم. ابتدا نگاهی به مشخصات این ستون بیندازیم:
</font>
</p>

In [4]:
df['constructionTime'].describe()

count    318819.000000
mean       1999.443744
std           8.586801
min        1906.000000
25%        1994.000000
50%        2002.000000
75%        2005.000000
max        2016.000000
Name: constructionTime, dtype: float64

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
​​همانطور که گفته شد برای گسسته‌سازی دو روش یکنواخت و مبتنی بر چندک وجود دارد. برای این ستون خاص، می‌توان زمان ساخت خانه‌ها را به دهه‌ای که در آن ساخته شده‌اند، تبدیل کرد. در نتیجه، از گسسته‌سازی یکنواخت استفاده می‌کنیم. به عنوان مثال خانه‌ای که در سال ۱۹۹۲ ساخته شده به دهه ۱۹۹۰ و خانه‌ای که در سال ۲۰۰۰ ساخته شده به دهه ۲۰۰۰، اختصاص پیدا می‌کند.​​قطعه کد زیر، این گسسته‌سازی را نشان می‌دهد:
</font>
</p>

In [5]:
# discretize constructionTime to constructionDecade
df['constructionDecade'] = df['constructionTime'].apply(lambda y: str(int(10 * np.floor(y / 10))))

df[['id', 'constructionTime', 'constructionDecade']].head()

             id  constructionTime constructionDecade
0  101084782030              2005               2000
1  101086012217              2004               2000
2  101086041636              2005               2000
3  101086406841              2008               2000
4  101086920653              1960               1960

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ویژگی‌های چندجمله‌ای
</font>
</h2>

In [6]:
from sklearn.preprocessing import PolynomialFeatures

# choosing some numeric columns
selected_columns = ['Lng', 'Lat', 'ladderRatio']
df1 = df[selected_columns]

# creating the polynomial features object for two-degree polynomial features
pf = PolynomialFeatures(degree=2, interaction_only=False, include_bias=False)

# fitting to the features
pf.fit(df1)

# creating polynomial features
poly_feats = pf.transform(df1)

# creating a dataframe with all the features
num_feats = poly_feats.shape[1]
df_transformed = pd.DataFrame(poly_feats, columns=[f'f_{i}' for i in range(1, num_feats + 1)])
df_transformed.columns = pf.get_feature_names_out()
df_transformed.head()

,Lng,Lat,ladderRatio,Lng^2,Lng Lat,Lng ladderRatio,Lat^2,Lat ladderRatio,ladderRatio^2
0,116.475489,40.019520,0.217,13566.539538,4661.293162,25.275181,1601.561981,8.684236,0.047089
1,116.453917,39.881534,0.667,13561.514785,4644.360850,77.674763,1590.536754,26.600983,0.444889
2,116.561978,39.877145,0.500,13586.694715,4648.158898,58.280989,1590.186693,19.938572,0.250000
3,116.438010,40.076114,0.273,13557.810173,4666.382963,31.787577,1606.094913,10.940779,0.074529
4,116.428392,39.886229,0.333,13555.570464,4643.889505,38.770655,1590.911264,13.282114,0.110889